# Generated by Django 6.1.1 on 2026-09-22 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_executivemember_bio_executivemember_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorialboardmember',
            name='role',
            field=models.CharField(choices=[('chief_editor', 'Editor-in-Chief'), ('assoc_editor', 'Associate Editor'), ('member', 'Editorial Member'), ('intl_member', 'Editorial Member (International)'), ('patron', 'Honorary Patron')], max_length=20),
        ),
    ]
