# Generated by Django 6.1.1 on 2026-09-29 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_newslettersubscriber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorialboardmember',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Editorial Board Member'},
        ),
        migrations.AddField(
            model_name='editorialboardmember',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10),
        ),
        migrations.AddField(
            model_name='editorialboardmember',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload editor photo. Defaults to gender avatar if blank.', null=True, upload_to='editorial/'),
        ),
        migrations.AlterField(
            model_name='editorialboardmember',
            name='role',
            field=models.CharField(choices=[('chief_editor', 'Chief Editor'), ('assoc_editor', 'Associate Editor'), ('member', 'Editorial Member'), ('intl_member', 'Editorial Member (International)'), ('patron', 'Honorary Patron')], max_length=20),
        ),
    ]
