# Generated by Django 5.2.7 on 2026-10-06 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_update_councillor_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='executivemember',
            name='achievements',
            field=models.TextField(blank=True, help_text='Major Professional Achievements', null=True),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='date_of_birth',
            field=models.CharField(blank=True, help_text='Date of birth', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='email',
            field=models.CharField(blank=True, help_text='Official email address(es)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='official_address',
            field=models.TextField(blank=True, help_text='Official address', null=True),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact number(s)', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='projects',
            field=models.TextField(blank=True, help_text='Key Research Projects', null=True),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='publications',
            field=models.TextField(blank=True, help_text='Key Research Publications', null=True),
        ),
        migrations.AddField(
            model_name='executivemember',
            name='qualification',
            field=models.CharField(blank=True, help_text='Academic qualifications', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='carouselslide',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='conferenceevent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='editorialboardmember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='executivemember',
            name='bio',
            field=models.TextField(blank=True, help_text='Detailed bio / profile description'),
        ),
        migrations.AlterField(
            model_name='executivemember',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='journalvolume',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='newslettersubscriber',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='pastbearer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='publicationbook',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='societyaward',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
